# For custom modification and defaults see hyprland wiki: https://wiki.hypr.land/Configuring
# Some sections have been modularized and added to the "conf" folder as seperate files

#-------------------------------------------------
# PROGRAMS
#-------------------------------------------------

$terminal = kitty
$fileManager = thunar
$menu = fuzzel

#-------------------------------------------------
# IMPORTS
#-------------------------------------------------

source = ~/.config/hypr/conf/look.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/window.conf

#-------------------------------------------------
# MONITORS
#-------------------------------------------------

monitor = , preferred, auto, 1
# monitor = HDMI-A-1, 1920x1080@143, 0x0, 1

#-------------------------------------------------
# AUTO START
#-------------------------------------------------

exec-once = wal -i ~/.config/Wallpapers/miku.jpg
exec-once = hyprpaper
exec-once = waybar
exec-once = swaync

#-------------------------------------------------
# ENVIRONMENT VARIABLES
#-------------------------------------------------

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#-------------------------------------------------
# INPUT
#-------------------------------------------------

input {
    follow_mouse = 1
    sensitivity = 0
}